# Generated by Django 4.0.1 on 2022-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='stock',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
