# Generated by Django 4.0.1 on 2022-03-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juego',
            options={'verbose_name': 'juego', 'verbose_name_plural': 'juegos'},
        ),
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(default='No disponible', upload_to='juegos'),
            preserve_default=False,
        ),
    ]
